version: "3.9"
services:
  app:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    container_name: fishing
    image: dimkohoncharov/fishing:latest
    volumes:
      - .:/app:cached
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
  nginx-proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
