---
# - name: "Provision instances"
#   hosts: masters:workers
#   become: true
#   vars_files:
#     - ./vars/settings.yml
#   roles:
#     - {role: "system", tags: "system"}
#     - {role: "docker", tags: "docker"}
#     - {role: "certbot", tags: "certbot"}
- name: "Init Swarm masters"
  hosts: masters
  become: true
  vars_files:
    - ./vars/settings.yml
  tasks:
    - name: Get private ip address
      ansible.builtin.debug: var=ansible_eth0.ipv4.address
      register: master_ipv4
    - name: Get Swarm membership
      ansible.builtin.shell:
        docker info --format {{ '{{.Swarm.ControlAvailable}}' }}
      register: is_master
    - name: Swarm init
      ansible.builtin.command:
        docker swarm init --advertise-addr {{ master_ipv4['ansible_eth0.ipv4.address'] }}
      when: is_master == true
    - name: Get Worker Token
      ansible.builtin.command:
        docker swarm join-token worker -q
      register: worker_token
    - name: Show Worker token
      ansible.builtin.debug:
        var=worker_token.stdout
    - name: Master token
      ansible.builtin.command: docker swarm join-token manager -q
      register: master_token
    - name: Show Master Token
      ansible.builtin.debug: var=master_token.stdout
- name: Join Swarm Cluster
  hosts: workers
  become: true
  vars_files:
    - ./vars/settings.yml
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['master_ipv4']['ansible_eth0.ipv4.address'] }}"
  tasks:
    - name: Show master ip address
      ansible.builtin.debug: var=master
    - name: Get ip address
      ansible.builtin.debug: var=ansible_eth0.ipv4.address
    - name: Get status of worker
      ansible.builtin.command: docker info --format {{ '{{.Swarm.LocalNodeState}}' }}
      register: worker_status
    - name: check status
      ansible.builtin.debug: var=worker_status
    - name: Try to leave Swarm cluster
      ansible.builtin.command: docker swarm leave
      when: worker_status.stdout == 'error'
    - name: Join Swarm Cluster as a Worker
      ansible.builtin.command: docker swarm join --token {{ token }} {{ master }}:2377
      when: worker_status.stdout != 'active'
      register: worker
    - name: Show Results
      ansible.builtin.debug: var=worker.stdout
    - name: Show Errors
      ansible.builtin.debug: var=worker.stderr
